/* The following code was generated by JFlex 1.4.3 on 31/05/18 16:04 */

package br.com.uece.compilador.compiladorweb.scanner;

import br.com.uece.compilador.compiladorweb.parser.sym;
import br.com.uece.compilador.compiladorweb.throwables.CompiladorException;
import br.com.uece.compilador.compiladorweb.throwables.LexicalCompiladorException;
import java_cup.runtime.Symbol;

// importações que deveram existir no scanner /\


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 31/05/18 16:04 from the specification file
 * <tt>src/scanner/minijava.jflex</tt>
 */
public final class scanner implements java_cup.runtime.Scanner {

    /**
     * This character denotes the end of file
     */
    public static final int YYEOF = -1;

    /**
     * initial size of the lookahead buffer
     */
    private static final int ZZ_BUFFERSIZE = 16384;

    /**
     * lexical states
     */
    public static final int YYINITIAL = 0;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
     * at the beginning of a line
     * l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = {
            0, 0
    };

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED =
            "\11\0\1\4\1\3\2\0\1\3\22\0\1\4\1\42\4\0\1\41" +
                    "\1\0\1\46\1\47\1\6\1\37\1\44\1\40\1\36\1\5\12\2" +
                    "\1\0\1\54\1\43\1\45\3\0\22\1\1\23\7\1\1\50\1\0" +
                    "\1\51\1\0\1\55\1\0\1\16\1\12\1\26\1\30\1\15\1\21" +
                    "\1\24\1\34\1\7\2\1\1\14\1\31\1\10\1\13\1\25\1\1" +
                    "\1\17\1\22\1\11\1\20\1\27\1\33\1\32\1\35\1\1\1\52" +
                    "\1\0\1\53\uff82\0";

    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 =
            "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\17\2" +
                    "\1\6\1\7\1\10\1\1\1\11\1\12\1\13\1\14" +
                    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\2\0" +
                    "\1\2\1\24\21\2\1\25\1\26\1\0\1\27\1\30" +
                    "\20\2\1\31\1\32\2\2\1\33\10\2\1\34\1\35" +
                    "\5\2\1\36\4\2\1\37\1\40\1\2\1\41\1\2" +
                    "\1\42\1\43\1\44\1\2\1\45\1\46\1\47\14\0" +
                    "\1\50";

    private static int[] zzUnpackAction() {
        int[] result = new int[129];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\56\0\134\0\212\0\270\0\346\0\56\0\u0114" +
                    "\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284" +
                    "\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398\0\56\0\56" +
                    "\0\56\0\u03c6\0\56\0\56\0\56\0\56\0\56\0\56" +
                    "\0\56\0\56\0\56\0\56\0\56\0\u03f4\0\u0422\0\u0450" +
                    "\0\134\0\u047e\0\u04ac\0\u04da\0\u0508\0\u0536\0\u0564\0\u0592" +
                    "\0\u05c0\0\u05ee\0\u061c\0\u064a\0\u0678\0\u06a6\0\u06d4\0\u0702" +
                    "\0\u0730\0\u075e\0\56\0\56\0\u078c\0\134\0\134\0\u07ba" +
                    "\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a" +
                    "\0\u0958\0\u0986\0\u09b4\0\u09e2\0\u0a10\0\u0a3e\0\u0a6c\0\134" +
                    "\0\134\0\u0a9a\0\u0ac8\0\134\0\u0af6\0\u0b24\0\u0b52\0\u0b80" +
                    "\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\134\0\134\0\u0c66\0\u0c94" +
                    "\0\u0cc2\0\u0cf0\0\u0d1e\0\134\0\u0d4c\0\u0d7a\0\u0da8\0\u0dd6" +
                    "\0\134\0\134\0\u0e04\0\134\0\u0e32\0\134\0\134\0\134" +
                    "\0\u0e60\0\134\0\134\0\134\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18" +
                    "\0\u0f46\0\u0f74\0\u0fa2\0\u0fd0\0\u0ffe\0\u102c\0\u105a\0\u1088" +
                    "\0\56";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[129];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;  /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0 =
            "\1\2\1\3\1\4\2\5\1\6\1\7\1\10\1\11" +
                    "\1\12\1\13\1\3\1\14\1\15\1\3\1\16\1\3" +
                    "\1\17\1\20\1\21\1\3\1\22\1\23\1\24\1\3" +
                    "\1\25\1\3\1\26\2\3\1\27\1\30\1\31\1\32" +
                    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42" +
                    "\1\43\1\44\1\45\1\2\57\0\2\3\4\0\27\3" +
                    "\17\0\1\3\2\0\1\4\56\0\2\5\56\0\1\46" +
                    "\1\47\50\0\2\3\4\0\1\3\1\50\10\3\1\51" +
                    "\14\3\17\0\1\3\1\0\2\3\4\0\6\3\1\52" +
                    "\20\3\17\0\1\3\1\0\2\3\4\0\10\3\1\53" +
                    "\14\3\1\54\1\3\17\0\1\3\1\0\2\3\4\0" +
                    "\4\3\1\55\22\3\17\0\1\3\1\0\2\3\4\0" +
                    "\6\3\1\56\20\3\17\0\1\3\1\0\2\3\4\0" +
                    "\5\3\1\57\15\3\1\60\3\3\17\0\1\3\1\0" +
                    "\2\3\4\0\6\3\1\61\20\3\17\0\1\3\1\0" +
                    "\2\3\4\0\7\3\1\62\17\3\17\0\1\3\1\0" +
                    "\2\3\4\0\2\3\1\63\24\3\17\0\1\3\1\0" +
                    "\2\3\4\0\2\3\1\64\23\3\1\65\17\0\1\3" +
                    "\1\0\2\3\4\0\11\3\1\66\15\3\17\0\1\3" +
                    "\1\0\2\3\4\0\5\3\1\67\21\3\17\0\1\3" +
                    "\1\0\2\3\4\0\4\3\1\70\22\3\17\0\1\3" +
                    "\1\0\2\3\4\0\7\3\1\71\17\3\17\0\1\3" +
                    "\1\0\2\3\4\0\25\3\1\72\1\3\17\0\1\3" +
                    "\41\0\1\73\14\0\3\46\1\74\52\46\6\47\1\75" +
                    "\47\47\1\0\2\3\4\0\2\3\1\76\24\3\17\0" +
                    "\1\3\1\0\2\3\4\0\24\3\1\77\2\3\17\0" +
                    "\1\3\1\0\2\3\4\0\11\3\1\100\15\3\17\0" +
                    "\1\3\1\0\2\3\4\0\1\101\26\3\17\0\1\3" +
                    "\1\0\2\3\4\0\4\3\1\102\22\3\17\0\1\3" +
                    "\1\0\2\3\4\0\1\3\1\103\25\3\17\0\1\3" +
                    "\1\0\2\3\4\0\13\3\1\104\13\3\17\0\1\3" +
                    "\1\0\2\3\4\0\2\3\1\105\24\3\17\0\1\3" +
                    "\1\0\2\3\4\0\2\3\1\106\24\3\17\0\1\3" +
                    "\1\0\2\3\4\0\5\3\1\107\21\3\17\0\1\3" +
                    "\1\0\2\3\4\0\7\3\1\110\17\3\17\0\1\3" +
                    "\1\0\2\3\4\0\10\3\1\111\16\3\17\0\1\3" +
                    "\1\0\2\3\4\0\13\3\1\112\13\3\17\0\1\3" +
                    "\1\0\2\3\4\0\3\3\1\113\23\3\17\0\1\3" +
                    "\1\0\2\3\4\0\7\3\1\114\17\3\17\0\1\3" +
                    "\1\0\2\3\4\0\1\115\26\3\17\0\1\3\1\0" +
                    "\2\3\4\0\1\116\26\3\17\0\1\3\1\0\2\3" +
                    "\4\0\1\117\26\3\17\0\1\3\5\47\1\74\50\47" +
                    "\1\0\2\3\4\0\6\3\1\120\20\3\17\0\1\3" +
                    "\1\0\2\3\4\0\13\3\1\121\13\3\17\0\1\3" +
                    "\1\0\2\3\4\0\5\3\1\122\21\3\17\0\1\3" +
                    "\1\0\2\3\4\0\15\3\1\123\11\3\17\0\1\3" +
                    "\1\0\2\3\4\0\6\3\1\124\20\3\17\0\1\3" +
                    "\1\0\2\3\4\0\6\3\1\125\20\3\17\0\1\3" +
                    "\1\0\2\3\4\0\11\3\1\126\15\3\17\0\1\3" +
                    "\1\0\2\3\4\0\13\3\1\127\13\3\17\0\1\3" +
                    "\1\0\2\3\4\0\2\3\1\130\24\3\17\0\1\3" +
                    "\1\0\2\3\4\0\1\131\26\3\17\0\1\3\1\0" +
                    "\2\3\4\0\2\3\1\132\24\3\17\0\1\3\1\0" +
                    "\2\3\4\0\5\3\1\133\21\3\17\0\1\3\1\0" +
                    "\2\3\4\0\13\3\1\134\13\3\17\0\1\3\1\0" +
                    "\2\3\4\0\21\3\1\135\5\3\17\0\1\3\1\0" +
                    "\2\3\4\0\1\3\1\136\25\3\17\0\1\3\1\0" +
                    "\2\3\4\0\5\3\1\137\21\3\17\0\1\3\1\0" +
                    "\2\3\4\0\6\3\1\140\20\3\17\0\1\3\1\0" +
                    "\2\3\4\0\2\3\1\141\24\3\17\0\1\3\1\0" +
                    "\2\3\4\0\1\3\1\142\25\3\17\0\1\3\1\0" +
                    "\2\3\4\0\10\3\1\143\16\3\17\0\1\3\1\0" +
                    "\2\3\4\0\6\3\1\144\20\3\17\0\1\3\1\0" +
                    "\2\3\4\0\1\145\26\3\17\0\1\3\1\0\2\3" +
                    "\4\0\1\3\1\146\25\3\17\0\1\3\1\0\2\3" +
                    "\4\0\6\3\1\147\20\3\17\0\1\3\1\0\2\3" +
                    "\4\0\1\150\26\3\17\0\1\3\1\0\2\3\4\0" +
                    "\13\3\1\151\13\3\17\0\1\3\1\0\2\3\4\0" +
                    "\6\3\1\152\20\3\17\0\1\3\1\0\2\3\4\0" +
                    "\7\3\1\153\17\3\17\0\1\3\1\0\2\3\4\0" +
                    "\25\3\1\154\1\3\17\0\1\3\1\0\2\3\4\0" +
                    "\21\3\1\155\5\3\17\0\1\3\1\0\2\3\4\0" +
                    "\1\3\1\156\25\3\17\0\1\3\1\0\2\3\4\0" +
                    "\17\3\1\157\7\3\17\0\1\3\1\0\2\3\4\0" +
                    "\15\3\1\160\11\3\17\0\1\3\1\0\2\3\4\0" +
                    "\22\3\1\161\4\3\17\0\1\3\1\0\2\3\4\0" +
                    "\17\3\1\162\7\3\17\0\1\3\1\0\2\3\4\0" +
                    "\1\3\1\163\25\3\17\0\1\3\1\0\2\3\4\0" +
                    "\13\3\1\164\13\3\17\0\1\3\1\0\2\3\2\165" +
                    "\2\0\27\3\1\166\16\0\1\3\3\0\2\165\31\0" +
                    "\1\166\22\0\2\166\6\0\1\167\62\0\1\170\46\0" +
                    "\1\171\47\0\2\171\31\0\1\172\22\0\2\172\20\0" +
                    "\1\173\47\0\1\174\45\0\1\175\56\0\1\176\56\0" +
                    "\1\177\60\0\1\200\51\0\1\201\45\0";

    private static int[] zzUnpackTrans() {
        int[] result = new int[4278];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = {
            "Unkown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
    };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 =
            "\1\0\1\11\4\1\1\11\17\1\3\11\1\1\13\11" +
                    "\2\0\23\1\2\11\1\0\67\1\14\0\1\11";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[129];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * the input device
     */
    private java.io.Reader zzReader;

    /**
     * the current state of the DFA
     */
    private int zzState;

    /**
     * the current lexical state
     */
    private int zzLexicalState = YYINITIAL;

    /**
     * this buffer contains the current text to be matched and is
     * the source of the yytext() string
     */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

    /**
     * the textposition at the last accepting state
     */
    private int zzMarkedPos;

    /**
     * the current text position in the buffer
     */
    private int zzCurrentPos;

    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private int zzStartRead;

    /**
     * endRead marks the last character in the buffer, that has been read
     * from input
     */
    private int zzEndRead;

    /**
     * number of newlines encountered up to the start of the matched text
     */
    private int yyline;

    /**
     * the number of characters up to the start of the matched text
     */
    private int yychar;

    /**
     * the number of characters from the last newline up to the start of the
     * matched text
     */
    private int yycolumn;

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;

    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private boolean zzAtEOF;

    /**
     * denotes if the user-EOF-code has already been executed
     */
    private boolean zzEOFDone;

    /* user code: */
    // cria token
    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }


    // Método que imprime as Tokens

    public String symbolToString(Symbol s) {
        switch (s.sym) {
            //+
            case sym.PLUS:
                return "PLUS";
            //-
            case sym.MINUS:
                return "MINUS";
            //*
            case sym.TIMES:
                return "TIMES";

            case sym.BECOMES:
                return "BECOMES";

            //;
            case sym.SEMICOLON:
                return "SEMICOLON";
            //&&
            case sym.AND:
                return "AND";

            //return
            case sym.RETURN:
                return "RETURN";
            //id
            case sym.IDENTIFIER:
                return "ID(" + (String) s.value + ")";
            // string que representa um inteiro
            case sym.INTEGER_LITERAL:
                return "INTEGER_LITERAL(" + s.value + ")";
            //boolean
            case sym.BOOLEAN_TYPE:
                return "BOOLEAN";
            //int
            case sym.INTEGER_TYPE:
                return "INTEGER";
            //if
            case sym.IF:
                return "IF";
            // !
            case sym.NOT:
                return "NOT";
            //. do ponto flutuante
            case sym.DOT:
                return "DOT";
            //,
            case sym.COMMA:
                return "COMMA";
            //string
            case sym.STRING:
                return "STRING";
            //sout
            case sym.SYSTEM_OUT_PRINTLN:
                return "SYSTEM_OUT_PRINTLN";
            //else se nao
            case sym.ELSE:
                return "ELSE";
            //while iterador
            case sym.WHILE:
                return "WHILE";
            //class cabeçalho de uma classe
            case sym.CLASS:
                return "CLASS";
            // classes extends de outras classes
            case sym.EXTENDS:
                return "EXTENDS";
            //public  assinatura classe, metodo e variavel
            case sym.PUBLIC:
                return "PUBLIC";
            //static assinatura classe, metodo e variavel
            case sym.STATIC:
                return "STATIC";
            //return void
            case sym.VOID:
                return "VOID";
            //metodo main
            case sym.MAIN:
                return "MAIN";
            //true
            case sym.TRUE:
                return "TRUE";
            //false
            case sym.FALSE:
                return "FALSE";
            //length de um vetor/arraylist
            case sym.LENGTH:
                return "LENGTH";
            // contexto daquele objeto
            case sym.THIS:
                return "THIS";
            //new de um objeto
            case sym.NEW:
                return "NEW";
            //(
            case sym.LPAREN:
                return "LPAREN";
            //)
            case sym.RPAREN:
                return "RPAREN";
            //[
            case sym.LBRACKET:
                return "LBRACKET";
            //]
            case sym.RBRACKET:
                return "RBRACKET";
            //{
            case sym.LBRACE:
                return "LBRACE";
            //}
            case sym.RBRACE:
                return "RBRACE";
            //<
            case sym.LT:
                return "LT";
            //final
            case sym.EOF:
                return "<EOF>";
            //erro
            case sym.error:
                return "<ERROR>";
            //se nao entrar em nenhum dessas casos, é pq nao é uma token definida
            default:
                return "<UNEXPECTED TOKEN " + s.toString() + ">";
        }
    }


    /**
     * Creates a new scanner
     * There is also a java.io.InputStream version of this constructor.
     *
     * @param in the java.io.Reader to read input from.
     */
    public scanner(java.io.Reader in) {
        this.zzReader = in;
    }

    /**
     * Creates a new scanner.
     * There is also java.io.Reader version of this constructor.
     *
     * @param in the java.io.Inputstream to read input from.
     */
    public scanner(java.io.InputStream in) {
        this(new java.io.InputStreamReader(in));
    }

    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(String packed) {
        char[] map = new char[0x10000];
        int i = 0;  /* index in packed string  */
        int j = 0;  /* index in unpacked array */
        while (i < 126) {
            int count = packed.charAt(i++);
            char value = packed.charAt(i++);
            do map[j++] = value; while (--count > 0);
        }
        return map;
    }


    /**
     * Refills the input buffer.
     *
     * @return <code>false</code>, iff there was new input.
     * @throws java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {

        /* first: make room (if you can) */
        if (zzStartRead > 0) {
            System.arraycopy(zzBuffer, zzStartRead,
                    zzBuffer, 0,
                    zzEndRead - zzStartRead);

            /* translate stored positions */
            zzEndRead -= zzStartRead;
            zzCurrentPos -= zzStartRead;
            zzMarkedPos -= zzStartRead;
            zzStartRead = 0;
        }

        /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.length) {
            /* if not: blow it up */
            char newBuffer[] = new char[zzCurrentPos * 2];
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
            zzBuffer = newBuffer;
        }

        /* finally: fill the buffer with new input */
        int numRead = zzReader.read(zzBuffer, zzEndRead,
                zzBuffer.length - zzEndRead);

        if (numRead > 0) {
            zzEndRead += numRead;
            return false;
        }
        // unlikely but not impossible: read 0 characters, but not at end of stream
        if (numRead == 0) {
            int c = zzReader.read();
            if (c == -1) {
                return true;
            } else {
                zzBuffer[zzEndRead++] = (char) c;
                return false;
            }
        }

        // numRead < 0
        return true;
    }


    /**
     * Closes the input stream.
     */
    public final void close() throws java.io.IOException {
        zzAtEOF = true;            /* indicate end of file */
        zzEndRead = zzStartRead;  /* invalidate buffer    */

        if (zzReader != null)
            zzReader.close();
    }


    /**
     * Resets the scanner to read from a new input stream.
     * Does not close the old reader.
     * <p>
     * All internal variables are reset, the old input stream
     * <b>cannot</b> be reused (internal buffer is discarded and lost).
     * Lexical state is set to <tt>ZZ_INITIAL</tt>.
     *
     * @param reader the new input stream
     */
    public final void yyreset(java.io.Reader reader) {
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
        zzEOFDone = false;
        zzEndRead = zzStartRead = 0;
        zzCurrentPos = zzMarkedPos = 0;
        yyline = yychar = yycolumn = 0;
        zzLexicalState = YYINITIAL;
    }


    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }


    /**
     * Returns the character at position <tt>pos</tt> from the
     * matched text.
     * <p>
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     *            A value from 0 to yylength()-1.
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBuffer[zzStartRead + pos];
    }


    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }


    /**
     * Reports an error that occured while scanning.
     * <p>
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     * <p>
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     * <p>
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again.
     *               This number must not be greater than yylength()!
     */
    public void yypushback(int number) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG);

        zzMarkedPos -= number;
    }


    /**
     * Contains user EOF-code, which will be executed exactly once,
     * when the end of file is reached
     */
    private void zzDoEOF() throws java.io.IOException {
        if (!zzEOFDone) {
            zzEOFDone = true;
            close();
        }
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @throws java.io.IOException if any I/O-Error occurs
     */
    public java_cup.runtime.Symbol next_token() throws java.io.IOException, CompiladorException, LexicalCompiladorException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        char[] zzCMapL = ZZ_CMAP;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            boolean zzR = false;
            for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                 zzCurrentPosL++) {
                switch (zzBufferL[zzCurrentPosL]) {
                    case '\u000B':
                    case '\u000C':
                    case '\u0085':
                    case '\u2028':
                    case '\u2029':
                        yyline++;
                        yycolumn = 0;
                        zzR = false;
                        break;
                    case '\r':
                        yyline++;
                        yycolumn = 0;
                        zzR = true;
                        break;
                    case '\n':
                        if (zzR)
                            zzR = false;
                        else {
                            yyline++;
                            yycolumn = 0;
                        }
                        break;
                    default:
                        zzR = false;
                        yycolumn++;
                }
            }

            if (zzR) {
                // peek one character ahead if it is \n (if we have counted one line too much)
                boolean zzPeek;
                if (zzMarkedPosL < zzEndReadL)
                    zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                else if (zzAtEOF)
                    zzPeek = false;
                else {
                    boolean eof = zzRefill();
                    zzEndReadL = zzEndRead;
                    zzMarkedPosL = zzMarkedPos;
                    zzBufferL = zzBuffer;
                    if (eof)
                        zzPeek = false;
                    else
                        zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                }
                if (zzPeek) yyline--;
            }
            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];


            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL)
                        zzInput = zzBufferL[zzCurrentPosL++];
                    else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = zzBufferL[zzCurrentPosL++];
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;

                    int zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) break zzForAction;
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                case 4: { /* ignore whitespace */
                }
                case 41:
                    break;
                case 22: { /* do nothing */
                }
                case 42:
                    break;
                case 31: {
                    return symbol(sym.CLASS);
                }
                case 43:
                    break;
                case 14: {
                    return symbol(sym.RPAREN);
                }
                case 44:
                    break;
                case 38: {
                    return symbol(sym.BOOLEAN_TYPE);
                }
                case 45:
                    break;
                case 33: {
                    return symbol(sym.LENGTH);
                }
                case 46:
                    break;
                case 10: {
                    return symbol(sym.LT);
                }
                case 47:
                    break;
                case 17: {
                    return symbol(sym.LBRACE);
                }
                case 48:
                    break;
                case 15: {
                    return symbol(sym.LBRACKET);
                }
                case 49:
                    break;
                case 9: {
                    return symbol(sym.NOT);
                }
                case 50:
                    break;
                case 21: {
                    return symbol(sym.AND);
                }
                case 51:
                    break;
                case 34: {
                    return symbol(sym.RETURN);
                }
                case 52:
                    break;
                case 7: {
                    return symbol(sym.PLUS);
                }
                case 53:
                    break;
                case 3: {
                    return symbol(sym.INTEGER_LITERAL, new Integer(yytext()));
                }
                case 54:
                    break;
                case 39: {
                    return symbol(sym.EXTENDS);
                }
                case 55:
                    break;
                case 25: {
                    return symbol(sym.TRUE);
                }
                case 56:
                    break;
                case 12: {
                    return symbol(sym.BECOMES);
                }
                case 57:
                    break;
                case 1: {
                    System.err.println(
                            "Warning: ignoring invalid token at line " +
                                    (yyline + 1) +
                                    ", column " +
                                    (yycolumn + 1) +
                                    "."
                    );

                    // Do not return any tokens
                }
                case 58:
                    break;
                case 28: {
                    return symbol(sym.VOID);
                }
                case 59:
                    break;
                case 2: {
                    return symbol(sym.IDENTIFIER, yytext());
                }
                case 60:
                    break;
                case 5: {
                    return symbol(sym.TIMES);
                }
                case 61:
                    break;
                case 29: {
                    return symbol(sym.MAIN);
                }
                case 62:
                    break;
                case 16: {
                    return symbol(sym.RBRACKET);
                }
                case 63:
                    break;
                case 27: {
                    return symbol(sym.ELSE);
                }
                case 64:
                    break;
                case 35: {
                    return symbol(sym.STATIC);
                }
                case 65:
                    break;
                case 32: {
                    return symbol(sym.WHILE);
                }
                case 66:
                    break;
                case 20: {
                    return symbol(sym.IF);
                }
                case 67:
                    break;
                case 13: {
                    return symbol(sym.LPAREN);
                }
                case 68:
                    break;
                case 26: {
                    return symbol(sym.THIS);
                }
                case 69:
                    break;
                case 23: {
                    return symbol(sym.INTEGER_TYPE);
                }
                case 70:
                    break;
                case 18: {
                    return symbol(sym.RBRACE);
                }
                case 71:
                    break;
                case 19: {
                    return symbol(sym.SEMICOLON);
                }
                case 72:
                    break;
                case 8: {
                    return symbol(sym.MINUS);
                }
                case 73:
                    break;
                case 40: {
                    return symbol(sym.SYSTEM_OUT_PRINTLN);
                }
                case 74:
                    break;
                case 24: {
                    return symbol(sym.NEW);
                }
                case 75:
                    break;
                case 36: {
                    return symbol(sym.STRING);
                }
                case 76:
                    break;
                case 11: {
                    return symbol(sym.COMMA);
                }
                case 77:
                    break;
                case 30: {
                    return symbol(sym.FALSE);
                }
                case 78:
                    break;
                case 37: {
                    return symbol(sym.PUBLIC);
                }
                case 79:
                    break;
                case 6: {
                    return symbol(sym.DOT);
                }
                case 80:
                    break;
                default:
                    if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                        zzAtEOF = true;
                        zzDoEOF();
                        {
                            return new java_cup.runtime.Symbol(sym.EOF);
                        }
                    } else {
                        zzScanError(ZZ_NO_MATCH);
                    }
            }
        }
    }


}
