
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 31 16:04:04 GFT 2018
//----------------------------------------------------

package br.com.uece.compilador.compiladorweb.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 21;
  public static final int LPAREN = 23;
  public static final int MINUS = 31;
  public static final int STATIC = 9;
  public static final int RPAREN = 24;
  public static final int NOT = 36;
  public static final int SEMICOLON = 27;
  public static final int AND = 33;
  public static final int LT = 34;
  public static final int COMMA = 38;
  public static final int CLASS = 16;
  public static final int PLUS = 30;
  public static final int MAIN = 11;
  public static final int IF = 12;
  public static final int THIS = 7;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 22;
  public static final int TRUE = 5;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int BECOMES = 35;
  public static final int VOID = 10;
  public static final int INTEGER_TYPE = 2;
  public static final int TIMES = 32;
  public static final int LBRACE = 25;
  public static final int ELSE = 13;
  public static final int SYSTEM_OUT_PRINTLN = 20;
  public static final int WHILE = 14;
  public static final int PUBLIC = 8;
  public static final int RBRACE = 26;
  public static final int EXTENDS = 17;
  public static final int STRING = 3;
  public static final int FALSE = 6;
  public static final int LENGTH = 19;
  public static final int INTEGER_LITERAL = 28;
  public static final int BOOLEAN_TYPE = 4;
  public static final int IDENTIFIER = 29;
}

